# Generated by Django 5.0.1 on 2024-12-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('fecha_reserva', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad_personas', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO ASISTEN', 'No asisten')], default='RESERVADO', max_length=15)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
